-- Parking map tool: a large (30000x10000px) airfield apron diagram, served
-- as a Deep Zoom Image tile pyramid (generated by
-- scripts/generate-parking-tiles.mjs, uploaded by
-- scripts/upload-parking-tiles.mjs) with data-driven overlays for parking
-- spots and aircraft assignments. Publicly viewable; writes require a
-- signed-in editor, same pattern as warm_status_*. No author tracking -
-- this is editable public info, not an audit trail.

-- ---------------------------------------------------------------------------
-- Storage: public bucket holding the DZI tile pyramid. Only the upload
-- script (using the service role key, which bypasses RLS) writes to it, so
-- no authenticated write policy is needed - just public read so the map can
-- load tiles client-side.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('parking-map', 'parking-map', true)
on conflict (id) do nothing;

create policy "parking_map_tiles_select_public"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'parking-map');

-- ---------------------------------------------------------------------------
-- parking_aprons: named regions of the map. x/y/width/height are normalized
-- fractions (0..1) of the source image's width/height respectively - used
-- both to draw a "jump to this apron" viewport rect and to group spots.
-- ---------------------------------------------------------------------------
create table public.parking_aprons (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  label text not null,
  x double precision not null,
  y double precision not null,
  width double precision not null,
  height double precision not null,
  created_at timestamptz not null default now()
);

alter table public.parking_aprons enable row level security;

create policy "parking_aprons_select_public"
  on public.parking_aprons for select
  to anon, authenticated
  using (true);

create policy "parking_aprons_insert_authenticated"
  on public.parking_aprons for insert
  to authenticated
  with check (true);

create policy "parking_aprons_update_authenticated"
  on public.parking_aprons for update
  to authenticated
  using (true)
  with check (true);

create policy "parking_aprons_delete_authenticated"
  on public.parking_aprons for delete
  to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- parking_spots: individual spot markers within an apron. x/y are
-- normalized fractions (0..1) of the source image's width/height - the
-- icon anchor point.
-- ---------------------------------------------------------------------------
create table public.parking_spots (
  id uuid primary key default gen_random_uuid(),
  apron_id uuid not null references public.parking_aprons (id) on delete cascade,
  label text not null,
  x double precision not null,
  y double precision not null,
  created_at timestamptz not null default now()
);

create index parking_spots_apron_id_idx on public.parking_spots (apron_id);

alter table public.parking_spots enable row level security;

create policy "parking_spots_select_public"
  on public.parking_spots for select
  to anon, authenticated
  using (true);

create policy "parking_spots_insert_authenticated"
  on public.parking_spots for insert
  to authenticated
  with check (true);

create policy "parking_spots_update_authenticated"
  on public.parking_spots for update
  to authenticated
  using (true)
  with check (true);

create policy "parking_spots_delete_authenticated"
  on public.parking_spots for delete
  to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- parking_assignments: which aircraft occupies a spot, and when. end_time
-- null means "still parked / open-ended" - drives both the map's current-
-- occupant overlay and the occupancy timeline chart.
-- ---------------------------------------------------------------------------
create table public.parking_assignments (
  id uuid primary key default gen_random_uuid(),
  spot_id uuid not null references public.parking_spots (id) on delete cascade,
  aircraft text not null,
  start_time timestamptz not null,
  end_time timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  constraint end_after_start check (end_time is null or end_time > start_time)
);

create index parking_assignments_spot_id_idx on public.parking_assignments (spot_id);
create index parking_assignments_time_range_idx on public.parking_assignments (start_time, end_time);

alter table public.parking_assignments enable row level security;

create policy "parking_assignments_select_public"
  on public.parking_assignments for select
  to anon, authenticated
  using (true);

create policy "parking_assignments_insert_authenticated"
  on public.parking_assignments for insert
  to authenticated
  with check (true);

create policy "parking_assignments_update_authenticated"
  on public.parking_assignments for update
  to authenticated
  using (true)
  with check (true);

create policy "parking_assignments_delete_authenticated"
  on public.parking_assignments for delete
  to authenticated
  using (true);
